# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pr:
  branches:
    include:
    - master
  paths:
    include:
    - client

variables:
  directPath: client

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: npm install
  workingDirectory: $(directPath)

- script: npx ng build
  displayName: ng build
  workingDirectory: $(directPath)

- script: npx ng test --browsers ChromeHeadless --watch false --code-coverage
  displayName: ng test
  workingDirectory: $(directPath)

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Group4_P2_Sonar'
    organization: '210726-wvu-net-ext'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '210726-wvu-net-ext_P2-Ashlei-Yuriy-Dylan_Frontend'
    cliSources: 'client/src'
    extraProperties: |
      sonar.javascript.lcov.reportPaths=client/coverage/client/lcov.info
      sonar.coverage.exclusions=**/*.spec.ts
- task: SonarCloudAnalyze@1
  displayName: sonar run analysis

- task: SonarCloudPublish@1
  displayName: sonar publish analysis result
  inputs:
    pollingTimeoutSec: '300'