apiVersion: v1
kind: Service
metadata:
  name: chariots-back
  labels:
    app: chariots
    role: api
spec:
  type: NodePort
  selector:
    app: chariots
    role: api
  ports:
  - port: 80
    nodePort: 30005
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: chariots-back
  labels: 
    app: chariots
    role: api
spec: 
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 5
  selector: 
    matchLabels:
      app: chariots
      role: api
  template: 
    metadata:
      labels:
        app: chariots
        role: api
    spec: 
      containers: 
      - name: api
        image: mmookow/chariotsback:2.0
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: '64Mi'
            cpu: '100m'
          limits:
            memory: '512Mi'
            cpu: '1000m'
        livenessProbe:
          httpGet:
            port: 80
            path: /health
          periodSeconds: 30